version: '3.9'

services:
    mysql8:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: my_mysql8
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_DATABASE: belajar_laravel
            MYSQL_USER: password
            MYSQL_PASSWORD: password12345
            MYSQL_MAX_ALLOWED_PACKET: 256M
        ports:
            - '3306:3306'
        volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - ../belajar_laravel_docker_source/mysql_data80:/var/lib/mysql
        networks:
            - my_network

    php:
        container_name: my_php8
        working_dir: /var/www/html
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./public:/var/www/html/public
            - ./storage:/var/www/html/storage
        networks:
            - my_network
        ports:
            - '80:80'

networks:
    my_network:
